// <auto-generated />
using System;
using Hospital.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Migrations
{
    [DbContext(typeof(ChdbContext))]
    partial class ChdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Models.Medication", b =>
                {
                    b.Property<int>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("medication_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationId"));

                    b.Property<DateOnly?>("LastPrescribedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_prescribed_date");

                    b.Property<decimal?>("MedicationCost")
                        .HasColumnType("decimal(9, 2)")
                        .HasColumnName("medication_cost");

                    b.Property<string>("MedicationDescription")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("medication_description");

                    b.Property<string>("PackageSize")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("package_size");

                    b.Property<string>("Sig")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sig");

                    b.Property<string>("Strength")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("strength");

                    b.Property<int?>("UnitsUsedYtd")
                        .HasColumnType("int")
                        .HasColumnName("units_used_ytd");

                    b.HasKey("MedicationId")
                        .HasName("PK__medicati__DD94789BE1A77686");

                    b.ToTable("medications");
                });
#pragma warning restore 612, 618
        }
    }
}
